language: php

php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

script:
  # Update composer to latest version.
  - composer self-update || true
  # For faster installing
  - composer global require hirak/prestissimo
  # self install
  - composer global require folha/composer-plugin-qa dev-master
  # Validate composer.json file.
  - composer validate
  # Try to install all requirements.
  - composer update
  # Self QA
  - composer qa:code-beautifier-fixer
  - composer qa:code-sniffer
  - composer qa:copy-paste-detector
  - composer qa:line-of-code
  - composer qa:mess-detector
  - composer qa:security-checker
